# Map NodePorts on the host to the kind control-plane node
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
  - role: control-plane
    extraPortMappings:
      - containerPort: 30081  # xdata-app-0
        hostPort: 30081
        protocol: TCP
      - containerPort: 30082  # xdata-app-1
        hostPort: 30082
        protocol: TCP
      - containerPort: 30083  # xdata-app-2
        hostPort: 30083
        protocol: TCP